name: CI for .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Adjust to your .NET version (e.g., 6.0.x, 7.0.x)

    # Restore .NET dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the .NET project
    - name: Build .NET project
      run: dotnet build --configuration Release --no-restore